/* Contract test: the C++ encoder must reproduce, byte-for-byte, what the Python shore
 * decoder (shore/scout_shore/packet.py) expects. GOLDEN was generated by that Python encoder;
 * if this test fails, the two ends have drifted and the link is broken. */
#include <unity.h>

#include "scout_packet.h"

// From packet.py: Reading(buoy_id=1, ts=2027-03-01T00:00:00Z, seq=42, temp=26.44,
// turb=514, batt=3.28, uptime=75600, flags={SD_RETRY,BATT_LOW_SKIP_TX},
// soh={WATCHDOG_RESET,SD_INIT_FAIL}, audio=1, fw v0.1.0)
static const uint8_t GOLDEN[SCOUT_PACKET_SIZE] = {
    0x01, 0x01, 0x00, 0x00, 0xb5, 0x84, 0x6b, 0x2a, 0x00, 0x00,
    0x00, 0x54, 0x0a, 0x02, 0x02, 0xd0, 0x0c, 0x50, 0x27, 0x01,
    0x00, 0x09, 0x00, 0x05, 0x01, 0x00, 0x01, 0x00, 0x0d, 0x1f};

static ScoutReading golden_reading() {
    ScoutReading r;
    r.schema_version = SCOUT_PACKET_VERSION;
    r.buoy_id = 1;
    r.timestamp = 1803859200u;  // 2027-03-01T00:00:00Z
    r.record_seq = 42;
    r.temp_c_centi = scout_temp_centi(26.44f);
    r.turbidity_adc = 514;
    r.battery_mv = scout_battery_mv(3.28f);
    r.uptime_s = 75600;
    r.flags = SCOUT_FLAG_SD_RETRY | SCOUT_FLAG_BATT_LOW_SKIP_TX;
    r.soh = SCOUT_SOH_WATCHDOG_RESET | SCOUT_SOH_SD_INIT_FAIL;
    r.audio_present = 1;
    r.fw_major = 0;
    r.fw_minor = 1;
    r.fw_patch = 0;
    return r;
}

void test_encode_matches_shore_golden(void) {
    ScoutReading r = golden_reading();
    uint8_t buf[SCOUT_PACKET_SIZE];
    TEST_ASSERT_EQUAL_UINT(SCOUT_PACKET_SIZE, scout_packet_encode(&r, buf));
    TEST_ASSERT_EQUAL_HEX8_ARRAY(GOLDEN, buf, SCOUT_PACKET_SIZE);
}

void test_crc_of_body_is_known(void) {
    TEST_ASSERT_EQUAL_HEX16(0x1f0d, scout_crc16_ccitt(GOLDEN, SCOUT_PACKET_BODY_SIZE));
}

void test_fixed_point_helpers(void) {
    TEST_ASSERT_EQUAL_INT16(2644, scout_temp_centi(26.44f));
    TEST_ASSERT_EQUAL_INT16(-125, scout_temp_centi(-1.25f));
    TEST_ASSERT_EQUAL_UINT16(3280, scout_battery_mv(3.28f));
}

static void run_all() {
    UNITY_BEGIN();
    RUN_TEST(test_encode_matches_shore_golden);
    RUN_TEST(test_crc_of_body_is_known);
    RUN_TEST(test_fixed_point_helpers);
    UNITY_END();
}

#ifdef ARDUINO
#include <Arduino.h>
void setup() {
    delay(2000);
    run_all();
}
void loop() {}
#else
int main() {
    run_all();
    return 0;
}
#endif
